#!/usr/bin/env python3
"""
Setup Script for Automated YouTube Content System
Helps users set up the system with guided configuration
"""

import os
import sys


def print_banner():
    """Print welcome banner"""
    print("""
    ╔══════════════════════════════════════════════════════════════╗
    ║                                                              ║
    ║   🎬 Automated YouTube Content Creation System              ║
    ║      Setup Wizard                                           ║
    ║                                                              ║
    ╚══════════════════════════════════════════════════════════════╝
    """)


def check_dependencies():
    """Check if required dependencies are installed"""
    print("\n📋 Checking dependencies...\n")
    
    # Check Python version
    if sys.version_info < (3, 12):
        print("❌ Python 3.12 or 3.13 is required")
        print(f"   Current version: {sys.version}")
        return False
    if sys.version_info >= (3, 14):
        print("❌ Python 3.14+ is not supported")
        print("   Pillow and lxml do not provide prebuilt wheels for Python 3.14 yet.")
        print("   Please install Python 3.12 or 3.13 instead.")
        return False
    print(f"✓ Python {sys.version_info.major}.{sys.version_info.minor}")
    
    # Check ffmpeg
    import subprocess
    try:
        result = subprocess.run(['ffmpeg', '-version'], 
                              capture_output=True, text=True)
        print("✓ ffmpeg is installed")
    except FileNotFoundError:
        print("❌ ffmpeg is not installed")
        print("   Please install ffmpeg:")
        print("   - Ubuntu/Debian: sudo apt-get install ffmpeg")
        print("   - macOS: brew install ffmpeg")
        print("   - Windows: Download from https://ffmpeg.org/download.html")
        return False
    
    # Check required Python packages
    required_packages = [
        'flask', 'openai', 'google-api-python-client', 
        'gtts', 'moviepy', 'python-dotenv'
    ]
    
    missing_packages = []
    for package in required_packages:
        try:
            __import__(package.replace('-', '_'))
            print(f"✓ {package}")
        except ImportError:
            missing_packages.append(package)
            print(f"❌ {package}")
    
    if missing_packages:
        print(f"\n⚠️  Missing packages. Run: pip install -r requirements.txt")
        return False
    
    print("\n✅ All dependencies are installed!\n")
    return True


def create_env_file():
    """Create .env file with user input"""
    print("\n⚙️  Configuration Setup\n")
    print("I'll help you create the .env configuration file.\n")
    
    # Check if .env already exists
    if os.path.exists('.env'):
        response = input(".env file already exists. Overwrite? (y/N): ")
        if response.lower() != 'y':
            print("Keeping existing .env file")
            return
    
    config = {}
    
    # OpenAI API Key
    print("\n1. OpenAI API Key")
    print("   Get from: https://platform.openai.com/api-keys")
    config['OPENAI_API_KEY'] = input("   Enter your OpenAI API key: ").strip()
    
    # Amazon Affiliate Tag
    print("\n2. Amazon Affiliate Tag")
    print("   Get from: https://affiliate-program.amazon.com/")
    config['AMAZON_AFFILIATE_TAG'] = input("   Enter your Amazon affiliate tag: ").strip()
    
    # Content Topic
    print("\n3. Content Topic")
    print("   What topic should videos be about?")
    config['CONTENT_TOPIC'] = input("   Topic (default: technology): ").strip() or "technology"
    
    # Content Frequency
    print("\n4. Content Frequency")
    print("   How often should videos be created?")
    print("   Options: hourly, daily, weekly")
    config['CONTENT_FREQUENCY'] = input("   Frequency (default: daily): ").strip() or "daily"
    
    # Video Privacy
    print("\n5. Video Privacy")
    print("   What privacy setting for uploaded videos?")
    print("   Options: public, unlisted, private")
    config['VIDEO_PRIVACY'] = input("   Privacy (default: public): ").strip() or "public"
    
    # Write .env file
    with open('.env', 'w') as f:
        f.write("# Automated YouTube Content System Configuration\n")
        f.write("# Generated by setup.py\n\n")
        f.write(f"OPENAI_API_KEY={config['OPENAI_API_KEY']}\n")
        f.write(f"AMAZON_AFFILIATE_TAG={config['AMAZON_AFFILIATE_TAG']}\n")
        f.write(f"CONTENT_TOPIC={config['CONTENT_TOPIC']}\n")
        f.write(f"CONTENT_FREQUENCY={config['CONTENT_FREQUENCY']}\n")
        f.write(f"VIDEO_PRIVACY={config['VIDEO_PRIVACY']}\n\n")
        f.write("# Server Settings\n")
        f.write("FLASK_PORT=5000\n")
        f.write("FLASK_HOST=0.0.0.0\n")
    
    print("\n✅ .env file created successfully!\n")


def setup_youtube_credentials():
    """Guide user through YouTube API setup"""
    print("\n📺 YouTube API Setup\n")
    print("To upload videos to YouTube, you need OAuth credentials.\n")
    print("Steps:")
    print("1. Go to: https://console.cloud.google.com/")
    print("2. Create a new project or select existing one")
    print("3. Enable 'YouTube Data API v3'")
    print("4. Create OAuth 2.0 credentials")
    print("5. Download as 'client_secrets.json'")
    print("6. Place in this directory\n")
    
    if os.path.exists('client_secrets.json'):
        print("✅ client_secrets.json found!")
    else:
        print("⚠️  client_secrets.json not found")
        print("   You'll need this file to upload to YouTube\n")
    
    input("Press Enter to continue...")


def create_directories():
    """Create necessary directories"""
    print("\n📁 Creating directories...\n")
    
    dirs = ['generated_videos', 'generated_scripts', 'temp', 'templates']
    
    for dir_name in dirs:
        if not os.path.exists(dir_name):
            os.makedirs(dir_name)
            print(f"✓ Created {dir_name}/")
        else:
            print(f"✓ {dir_name}/ exists")
    
    print()


def main():
    """Main setup function"""
    print_banner()
    
    # Check dependencies
    if not check_dependencies():
        print("\n❌ Setup failed: Missing dependencies")
        print("   Please install missing dependencies and try again")
        sys.exit(1)
    
    # Create directories
    create_directories()
    
    # Create .env file
    create_env_file()
    
    # YouTube setup guide
    setup_youtube_credentials()
    
    # Final message
    print("\n" + "="*60)
    print("✅ Setup Complete!")
    print("="*60)
    print("\nNext steps:")
    print("1. Ensure client_secrets.json is in the project directory")
    print("2. Run the web dashboard: python app.py")
    print("3. Or create a video immediately: python create_video.py")
    print("\nDocumentation: See README.md for more details")
    print("="*60 + "\n")


if __name__ == '__main__':
    main()
